/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hectorrivera_lab6p2;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author hriverav
 */
public class fulbo extends javax.swing.JFrame {

    /**
     * Creates new form hectorrivera_lab6p2
     */
    public fulbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CrearJugadores = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_jugadores_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_jugadores_edad = new javax.swing.JSpinner();
        jComboBox_Jugadores_posicion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton_jugadores_add = new javax.swing.JButton();
        jDialog_CrearEquipo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_crearequipo_nombre = new javax.swing.JTextField();
        jTextField_crearEquipo_Cuidad = new javax.swing.JTextField();
        jTextField_crearEquipo_pais = new javax.swing.JTextField();
        jTextField_crearequipo_estadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_CrearEquipo_add = new javax.swing.JButton();
        jDialog_modificar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jTextField_mod_newname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_new_age = new javax.swing.JSpinner();
        jButton_change = new javax.swing.JButton();
        jDialog_Transferencia = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_transfer_equipos = new javax.swing.JTree();
        jButton_transfer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPopupMenu_transferencia_list = new javax.swing.JPopupMenu();
        jMenuItem_modificar = new javax.swing.JMenuItem();
        jMenuItem_Eliminar = new javax.swing.JMenuItem();
        jPopupMenu_transferencia_tree = new javax.swing.JPopupMenu();
        jMenuItem_tree_delete = new javax.swing.JMenuItem();
        jPanel_principal = new javax.swing.JPanel();
        Barcita = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar4 = new javax.swing.JToolBar();
        jButton_crearEquipo = new javax.swing.JButton();
        jButton_crearJugador = new javax.swing.JButton();
        jButton_transferencia = new javax.swing.JButton();
        jMenuBar_principal = new javax.swing.JMenuBar();
        jMenu_Opciones = new javax.swing.JMenu();
        jMenuItem_crearEquipo = new javax.swing.JMenuItem();
        jMenuItem_crearJugador = new javax.swing.JMenuItem();
        jMenuItem_Transferencia = new javax.swing.JMenuItem();
        jMenu_ayuda = new javax.swing.JMenu();

        jDialog_CrearJugadores.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Crear jugador");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("edad");

        jSpinner_jugadores_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        jComboBox_Jugadores_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("posicion");

        jButton_jugadores_add.setText("add");
        jButton_jugadores_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_jugadores_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(74, 74, 74))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_jugadores_name)
                            .addComponent(jSpinner_jugadores_edad)
                            .addComponent(jComboBox_Jugadores_posicion, 0, 130, Short.MAX_VALUE)))
                    .addComponent(jButton_jugadores_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_jugadores_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner_jugadores_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Jugadores_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jButton_jugadores_add)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_CrearJugadoresLayout = new javax.swing.GroupLayout(jDialog_CrearJugadores.getContentPane());
        jDialog_CrearJugadores.getContentPane().setLayout(jDialog_CrearJugadoresLayout);
        jDialog_CrearJugadoresLayout.setHorizontalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_CrearJugadoresLayout.setVerticalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog_CrearEquipo.setResizable(false);
        jDialog_CrearEquipo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Crear Equipo");

        jTextField_crearEquipo_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_crearEquipo_paisActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("pais");

        jLabel4.setText("cuidad");

        jLabel5.setText("Estadio");

        jButton_CrearEquipo_add.setText("Agregar");
        jButton_CrearEquipo_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearEquipo_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_CrearEquipo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_crearequipo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jTextField_crearEquipo_pais))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_crearEquipo_Cuidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextField_crearequipo_estadio)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearEquipo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearequipo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearEquipo_Cuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearequipo_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton_CrearEquipo_add)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jDialog_CrearEquipo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel12.setText("New Name");

        jLabel13.setText("New age");

        jSpinner_new_age.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        jButton_change.setText("Change");
        jButton_change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_changeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jButton_change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner_new_age)
                    .addComponent(jTextField_mod_newname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_mod_newname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner_new_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_change)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog_modificarLayout = new javax.swing.GroupLayout(jDialog_modificar.getContentPane());
        jDialog_modificar.getContentPane().setLayout(jDialog_modificarLayout);
        jDialog_modificarLayout.setHorizontalGroup(
            jDialog_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog_modificarLayout.setVerticalGroup(
            jDialog_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialog_Transferencia.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jTree_transfer_equipos.setBackground(new java.awt.Color(255, 255, 255));
        jTree_transfer_equipos.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("equipos");
        jTree_transfer_equipos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree_transfer_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree_transfer_equiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree_transfer_equipos);

        jButton_transfer.setText("------>");
        jButton_transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_transferMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Transferir");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Transferencia");

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_transfer)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_transfer)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jDialog_TransferenciaLayout = new javax.swing.GroupLayout(jDialog_Transferencia.getContentPane());
        jDialog_Transferencia.getContentPane().setLayout(jDialog_TransferenciaLayout);
        jDialog_TransferenciaLayout.setHorizontalGroup(
            jDialog_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_TransferenciaLayout.setVerticalGroup(
            jDialog_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem_modificar.setText("modificar");
        jMenuItem_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_modificarActionPerformed(evt);
            }
        });
        jPopupMenu_transferencia_list.add(jMenuItem_modificar);

        jMenuItem_Eliminar.setText("Eliminar");
        jMenuItem_Eliminar.setToolTipText("");
        jMenuItem_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EliminarActionPerformed(evt);
            }
        });
        jPopupMenu_transferencia_list.add(jMenuItem_Eliminar);

        jMenuItem_tree_delete.setText("Delete");
        jMenuItem_tree_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tree_deleteActionPerformed(evt);
            }
        });
        jPopupMenu_transferencia_tree.add(jMenuItem_tree_delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_principal.setBackground(new java.awt.Color(51, 102, 255));

        Barcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/download.jpg"))); // NOI18N

        jToolBar3.setBackground(new java.awt.Color(255, 51, 51));
        jToolBar3.setRollover(true);

        jToolBar4.setBackground(new java.awt.Color(51, 102, 255));
        jToolBar4.setRollover(true);
        jToolBar3.add(jToolBar4);

        jButton_crearEquipo.setBackground(new java.awt.Color(255, 51, 51));
        jButton_crearEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearEquipo.setText("Crear equipo");
        jButton_crearEquipo.setFocusable(false);
        jButton_crearEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_crearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearEquipoMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_crearEquipo);

        jButton_crearJugador.setBackground(new java.awt.Color(51, 51, 255));
        jButton_crearJugador.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearJugador.setText("Crear Jugador");
        jButton_crearJugador.setFocusable(false);
        jButton_crearJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_crearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearJugadorMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_crearJugador);

        jButton_transferencia.setBackground(new java.awt.Color(255, 255, 51));
        jButton_transferencia.setForeground(new java.awt.Color(0, 0, 0));
        jButton_transferencia.setText("Transferencia");
        jButton_transferencia.setFocusable(false);
        jButton_transferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_transferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_transferenciaMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_transferencia);

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(Barcita)
                .addGap(191, 191, 191))
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Barcita)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        jMenuBar_principal.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar_principal.setForeground(new java.awt.Color(0, 0, 0));

        jMenu_Opciones.setText("Opciones");

        jMenuItem_crearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearEquipo.setText("crear Equipo");
        jMenuItem_crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_crearEquipoActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_crearEquipo);

        jMenuItem_crearJugador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearJugador.setText("Crear Jugador");
        jMenuItem_crearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_crearJugadorActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_crearJugador);

        jMenuItem_Transferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Transferencia.setText("Transferencia");
        jMenuItem_Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TransferenciaActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_Transferencia);

        jMenuBar_principal.add(jMenu_Opciones);

        jMenu_ayuda.setText("Ayuda");
        jMenuBar_principal.add(jMenu_ayuda);

        setJMenuBar(jMenuBar_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_crearEquipoActionPerformed
        // TODO add your handling code here:
        jDialog_CrearEquipo.setVisible(true);
        jDialog_CrearEquipo.pack();
    }//GEN-LAST:event_jMenuItem_crearEquipoActionPerformed

    private void jButton_crearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearEquipoMouseClicked
        // TODO add your handling code here:
        jDialog_CrearEquipo.setVisible(true);
        jDialog_CrearEquipo.pack();
    }//GEN-LAST:event_jButton_crearEquipoMouseClicked

    private void jMenuItem_crearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_crearJugadorActionPerformed
        // TODO add your handling code here:
        jDialog_CrearJugadores.setVisible(true);
        jDialog_CrearJugadores.pack();
        
    }//GEN-LAST:event_jMenuItem_crearJugadorActionPerformed

    private void jButton_crearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearJugadorMouseClicked
        // TODO add your handling code here:
        jDialog_CrearJugadores.setVisible(true);
        jDialog_CrearJugadores.pack();
    }//GEN-LAST:event_jButton_crearJugadorMouseClicked

    private void jMenuItem_TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TransferenciaActionPerformed
        // TODO add your handling code here:
        jDialog_Transferencia.setVisible(true);
        jDialog_Transferencia.pack();
    }//GEN-LAST:event_jMenuItem_TransferenciaActionPerformed

    private void jButton_transferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_transferenciaMouseClicked
        // TODO add your handling code here:
        jDialog_Transferencia.setVisible(true);
        jDialog_Transferencia.pack();
    }//GEN-LAST:event_jButton_transferenciaMouseClicked

    private void jTextField_crearEquipo_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_crearEquipo_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_crearEquipo_paisActionPerformed

    private void jButton_CrearEquipo_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearEquipo_addMouseClicked
        // TODO add your handling code here:
        Equipos.add(new Equipo(jTextField_crearEquipo_pais.getText(), jTextField_crearequipo_nombre.getText(), jTextField_crearequipo_estadio.getText(), jTextField_crearEquipo_Cuidad.getText()));
        Equipo x = new Equipo(jTextField_crearEquipo_pais.getText(), jTextField_crearequipo_nombre.getText(), jTextField_crearequipo_estadio.getText(), jTextField_crearEquipo_Cuidad.getText());
        JOptionPane.showMessageDialog(jDialog_CrearEquipo, "se creo el equipo");
        jTextField_crearEquipo_Cuidad.setText("");
        jTextField_crearEquipo_pais.setText("");
        jTextField_crearequipo_estadio.setText("");
        jTextField_crearequipo_nombre.setText("");
        
        DefaultTreeModel arbol = (DefaultTreeModel) jTree_transfer_equipos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) arbol.getRoot();
        
        Equipo team = Equipos.get(Equipos.size()-1);
        boolean found = false;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (team.getPais().equals(raiz.getChildAt(i).toString())) {
                
                    DefaultMutableTreeNode newTeam = new DefaultMutableTreeNode(x);
                    ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(newTeam);
                    found = true;
            }
        }
        
        if (found==false) {
            DefaultMutableTreeNode newTeam = new DefaultMutableTreeNode(x);
            DefaultMutableTreeNode newpais = new DefaultMutableTreeNode(x.getPais());
            newpais.add(newTeam);
            raiz.add(newpais);
        }
        arbol.reload();
    }//GEN-LAST:event_jButton_CrearEquipo_addMouseClicked

    private void jButton_jugadores_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_jugadores_addMouseClicked
        // TODO add your handling code here:
        ArrayList<Character> array = new ArrayList();
         String text = jTextField_jugadores_name.getText();
        
        int cont = 0;
        for (int i = 0; i < text.length(); i++) {
            array.add(text.charAt(i));
        }
        for (int i = 0; i < array.size(); i++) {
            char x = array.get(i);
            if (x=='0'||x=='1'||x=='2'||x=='3'||x=='4'||x=='5'||x=='6'||x=='7'||x=='8'||x=='9') {
                array.remove(i);
                cont++;
            }
        }
        
        if (cont!=0) {
            JOptionPane.showMessageDialog(jDialog_CrearJugadores, "nombre incorrecto se a modificado");
        }
        
        String name="";
        
        for (int i = 0; i < array.size(); i++) {
            name+=array.get(i);
        }
        Jugadores.add(new Jugador(name, jComboBox_Jugadores_posicion.getSelectedItem().toString(),(Integer)jSpinner_jugadores_edad.getValue()));
        JOptionPane.showMessageDialog(jDialog_CrearJugadores, "se creo el jugador");
        jTextField_jugadores_name.setText("");
        
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.removeAllElements();
        model.addAll(Jugadores);
        jList1.setModel(model);
    }//GEN-LAST:event_jButton_jugadores_addMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (jList1.getSelectedIndex()!= -1) {
                jPopupMenu_transferencia_list.show(jList1, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jMenuItem_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EliminarActionPerformed
        // TODO add your handling code here:
        Jugadores.remove(jList1.getSelectedIndex());
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.removeAllElements();
        model.addAll(Jugadores);
        jList1.setModel(model);
        
    }//GEN-LAST:event_jMenuItem_EliminarActionPerformed

    private void jButton_transferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_transferMouseClicked

        Object v1 = jTree_transfer_equipos.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodoselecionado = (DefaultMutableTreeNode)v1;
        if ( nodoselecionado.getUserObject() instanceof Equipo && (jList1.getSelectedIndex()!=-1|| jTree_transfer_equipos.getSelectionPath().getLastPathComponent() != null)) {
            int selectedlist = jList1.getSelectedIndex();
            DefaultTreeModel model = (DefaultTreeModel) jTree_transfer_equipos.getModel();
            
        
            DefaultMutableTreeNode jugador = new DefaultMutableTreeNode(Jugadores.get(selectedlist).getName());
            boolean found = false;
        
            for (int i = 0; i < ((DefaultMutableTreeNode)jTree_transfer_equipos.getSelectionPath().getLastPathComponent()).getChildCount(); i++) {
                if(Jugadores.get(selectedlist).getPosicion().equals(((DefaultMutableTreeNode)jTree_transfer_equipos.getSelectionPath().getLastPathComponent()).getChildAt(i).toString()) ){
                    ((DefaultMutableTreeNode)((DefaultMutableTreeNode)jTree_transfer_equipos.getSelectionPath().getLastPathComponent()).getChildAt(i)).add(jugador);
                    found = true;
                }
            }
            if (found==false) {
                DefaultMutableTreeNode posicion = new DefaultMutableTreeNode(Jugadores.get(selectedlist).getPosicion());
                posicion.add(jugador);
                ((DefaultMutableTreeNode)jTree_transfer_equipos.getSelectionPath().getLastPathComponent()).add(posicion);
            }
            model.reload();
        }else{
            JOptionPane.showMessageDialog(jDialog_Transferencia, "Error");
        }
        
    }//GEN-LAST:event_jButton_transferMouseClicked

    private void jTree_transfer_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree_transfer_equiposMouseClicked
        // TODO add your handling code here:
        if (evt.getButton()==MouseEvent.BUTTON3) {
             Object v1 = jTree_transfer_equipos.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode nodoselecionado = (DefaultMutableTreeNode)v1;
            if ( nodoselecionado.getUserObject() instanceof Equipo) {
                jPopupMenu_transferencia_tree.show(jDialog_Transferencia, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTree_transfer_equiposMouseClicked

    private void jMenuItem_tree_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tree_deleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTreeModel model = (DefaultTreeModel) jTree_transfer_equipos.getModel();
        model.removeNodeFromParent((DefaultMutableTreeNode)jTree_transfer_equipos.getSelectionPath().getLastPathComponent());
    }//GEN-LAST:event_jMenuItem_tree_deleteActionPerformed

    private void jMenuItem_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_modificarActionPerformed
        // TODO add your handling code here:
        jTextField_mod_newname.setText(Jugadores.get(jList1.getSelectedIndex()).getName());
        jSpinner_new_age.setValue((Integer)Jugadores.get(jList1.getSelectedIndex()).getEdad());
        jDialog_modificar.pack();
        jDialog_modificar.show(true);
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem_modificarActionPerformed

    private void jButton_changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_changeMouseClicked
        // TODO add your handling code here:

        Jugadores.get(jList1.getSelectedIndex()).setEdad((Integer)jSpinner_new_age.getValue());
        String text = jTextField_mod_newname.getText();
        
        int cont = 0;
        
        for (int i = 0; i < text.length(); i++) {
            char x = text.charAt(i);
            if (x=='0'||x=='1'||x=='2'||x=='3'||x=='4'||x=='5'||x=='6'||x=='7'||x=='8'||x=='9') {
                cont++;
            }
        }
        
        if (cont==0) {
            Jugadores.get(jList1.getSelectedIndex()).setName(jTextField_mod_newname.getText());
        }else{
            JOptionPane.showMessageDialog(jDialog_modificar, "nombre incorrecto");
        }
        jDialog_modificar.show(false);    
  
        
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.removeAllElements();
        model.addAll(Jugadores);
        
    }//GEN-LAST:event_jButton_changeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fulbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcita;
    private javax.swing.JButton jButton_CrearEquipo_add;
    private javax.swing.JButton jButton_change;
    private javax.swing.JButton jButton_crearEquipo;
    private javax.swing.JButton jButton_crearJugador;
    private javax.swing.JButton jButton_jugadores_add;
    private javax.swing.JButton jButton_transfer;
    private javax.swing.JButton jButton_transferencia;
    private javax.swing.JComboBox<String> jComboBox_Jugadores_posicion;
    private javax.swing.JDialog jDialog_CrearEquipo;
    private javax.swing.JDialog jDialog_CrearJugadores;
    private javax.swing.JDialog jDialog_Transferencia;
    private javax.swing.JDialog jDialog_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar_principal;
    private javax.swing.JMenuItem jMenuItem_Eliminar;
    private javax.swing.JMenuItem jMenuItem_Transferencia;
    private javax.swing.JMenuItem jMenuItem_crearEquipo;
    private javax.swing.JMenuItem jMenuItem_crearJugador;
    private javax.swing.JMenuItem jMenuItem_modificar;
    private javax.swing.JMenuItem jMenuItem_tree_delete;
    private javax.swing.JMenu jMenu_Opciones;
    private javax.swing.JMenu jMenu_ayuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JPopupMenu jPopupMenu_transferencia_list;
    private javax.swing.JPopupMenu jPopupMenu_transferencia_tree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_jugadores_edad;
    private javax.swing.JSpinner jSpinner_new_age;
    private javax.swing.JTextField jTextField_crearEquipo_Cuidad;
    private javax.swing.JTextField jTextField_crearEquipo_pais;
    private javax.swing.JTextField jTextField_crearequipo_estadio;
    private javax.swing.JTextField jTextField_crearequipo_nombre;
    private javax.swing.JTextField jTextField_jugadores_name;
    private javax.swing.JTextField jTextField_mod_newname;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTree jTree_transfer_equipos;
    // End of variables declaration//GEN-END:variables
    public ArrayList<Jugador> Jugadores = new ArrayList();
    public ArrayList<Equipo> Equipos = new ArrayList();
    
    
}
