/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hectorrivera_lab6p2;

import java.util.ArrayList;

/**
 *
 * @author hriverav
 */
public class fulbo extends javax.swing.JFrame {

    /**
     * Creates new form hectorrivera_lab6p2
     */
    public fulbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CrearJugadores = new javax.swing.JDialog();
        jPanel_principal = new javax.swing.JPanel();
        Barcita = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar4 = new javax.swing.JToolBar();
        jButton_crearEquipo = new javax.swing.JButton();
        jButton_crearJugador = new javax.swing.JButton();
        jButton_transferencia = new javax.swing.JButton();
        jMenuBar_principal = new javax.swing.JMenuBar();
        jMenu_Opciones = new javax.swing.JMenu();
        jMenuItem_crearEquipo = new javax.swing.JMenuItem();
        jMenuItem_crearJugador = new javax.swing.JMenuItem();
        jMenuItem_Transferencia = new javax.swing.JMenuItem();
        jMenu_ayuda = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog_CrearJugadoresLayout = new javax.swing.GroupLayout(jDialog_CrearJugadores.getContentPane());
        jDialog_CrearJugadores.getContentPane().setLayout(jDialog_CrearJugadoresLayout);
        jDialog_CrearJugadoresLayout.setHorizontalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog_CrearJugadoresLayout.setVerticalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_principal.setBackground(new java.awt.Color(255, 255, 255));

        Barcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/download.jpg"))); // NOI18N

        jToolBar3.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar3.setRollover(true);

        jToolBar4.setBackground(new java.awt.Color(51, 102, 255));
        jToolBar4.setRollover(true);
        jToolBar3.add(jToolBar4);

        jButton_crearEquipo.setBackground(new java.awt.Color(255, 51, 51));
        jButton_crearEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearEquipo.setText("Crear equipo");
        jButton_crearEquipo.setFocusable(false);
        jButton_crearEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton_crearEquipo);

        jButton_crearJugador.setBackground(new java.awt.Color(51, 51, 255));
        jButton_crearJugador.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearJugador.setText("Crear Jugador");
        jButton_crearJugador.setFocusable(false);
        jButton_crearJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton_crearJugador);

        jButton_transferencia.setBackground(new java.awt.Color(255, 255, 51));
        jButton_transferencia.setForeground(new java.awt.Color(0, 0, 0));
        jButton_transferencia.setText("Transferencia");
        jButton_transferencia.setFocusable(false);
        jButton_transferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_transferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton_transferencia);

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(Barcita)
                .addGap(191, 191, 191))
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Barcita)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        jMenuBar_principal.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar_principal.setForeground(new java.awt.Color(0, 0, 0));

        jMenu_Opciones.setText("Opciones");

        jMenuItem_crearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearEquipo.setText("crear Equipo");
        jMenuItem_crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_crearEquipoActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_crearEquipo);

        jMenuItem_crearJugador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearJugador.setText("Crear Jugador");
        jMenu_Opciones.add(jMenuItem_crearJugador);

        jMenuItem_Transferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Transferencia.setText("Transferencia");
        jMenu_Opciones.add(jMenuItem_Transferencia);

        jMenuBar_principal.add(jMenu_Opciones);

        jMenu_ayuda.setText("Ayuda");
        jMenuBar_principal.add(jMenu_ayuda);

        setJMenuBar(jMenuBar_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_crearEquipoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem_crearEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fulbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcita;
    private javax.swing.JButton jButton_crearEquipo;
    private javax.swing.JButton jButton_crearJugador;
    private javax.swing.JButton jButton_transferencia;
    private javax.swing.JDialog jDialog_CrearJugadores;
    private javax.swing.JMenuBar jMenuBar_principal;
    private javax.swing.JMenuItem jMenuItem_Transferencia;
    private javax.swing.JMenuItem jMenuItem_crearEquipo;
    private javax.swing.JMenuItem jMenuItem_crearJugador;
    private javax.swing.JMenu jMenu_Opciones;
    private javax.swing.JMenu jMenu_ayuda;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Jugador> Jugadores = new ArrayList();
    
    
}
