/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hectorrivera_lab6p2;

import java.util.ArrayList;

/**
 *
 * @author hriverav
 */
public class fulbo extends javax.swing.JFrame {

    /**
     * Creates new form hectorrivera_lab6p2
     */
    public fulbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CrearJugadores = new javax.swing.JDialog();
        jDialog_CrearEquipo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_crearequipo_nombre = new javax.swing.JTextField();
        jTextField_crearEquipo_Cuidad = new javax.swing.JTextField();
        jTextField_crearEquipo_pais = new javax.swing.JTextField();
        jTextField_crearequipo_estadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_CrearEquipo_add = new javax.swing.JButton();
        jDialog_Transferencia = new javax.swing.JDialog();
        jPanel_principal = new javax.swing.JPanel();
        Barcita = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar4 = new javax.swing.JToolBar();
        jButton_crearEquipo = new javax.swing.JButton();
        jButton_crearJugador = new javax.swing.JButton();
        jButton_transferencia = new javax.swing.JButton();
        jMenuBar_principal = new javax.swing.JMenuBar();
        jMenu_Opciones = new javax.swing.JMenu();
        jMenuItem_crearEquipo = new javax.swing.JMenuItem();
        jMenuItem_crearJugador = new javax.swing.JMenuItem();
        jMenuItem_Transferencia = new javax.swing.JMenuItem();
        jMenu_ayuda = new javax.swing.JMenu();

        jDialog_CrearJugadores.setResizable(false);

        javax.swing.GroupLayout jDialog_CrearJugadoresLayout = new javax.swing.GroupLayout(jDialog_CrearJugadores.getContentPane());
        jDialog_CrearJugadores.getContentPane().setLayout(jDialog_CrearJugadoresLayout);
        jDialog_CrearJugadoresLayout.setHorizontalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog_CrearJugadoresLayout.setVerticalGroup(
            jDialog_CrearJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog_CrearEquipo.setResizable(false);
        jDialog_CrearEquipo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Crear Equipo");

        jTextField_crearEquipo_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_crearEquipo_paisActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("pais");

        jLabel4.setText("cuidad");

        jLabel5.setText("Estadio");

        jButton_CrearEquipo_add.setText("Agregar");
        jButton_CrearEquipo_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearEquipo_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_CrearEquipo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_crearequipo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_crearEquipo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_crearEquipo_Cuidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextField_crearequipo_estadio)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearEquipo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearequipo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearEquipo_Cuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_crearequipo_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton_CrearEquipo_add)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jDialog_CrearEquipo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jDialog_Transferencia.setResizable(false);

        javax.swing.GroupLayout jDialog_TransferenciaLayout = new javax.swing.GroupLayout(jDialog_Transferencia.getContentPane());
        jDialog_Transferencia.getContentPane().setLayout(jDialog_TransferenciaLayout);
        jDialog_TransferenciaLayout.setHorizontalGroup(
            jDialog_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog_TransferenciaLayout.setVerticalGroup(
            jDialog_TransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_principal.setBackground(new java.awt.Color(51, 102, 255));

        Barcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/download.jpg"))); // NOI18N

        jToolBar3.setBackground(new java.awt.Color(255, 51, 51));
        jToolBar3.setRollover(true);

        jToolBar4.setBackground(new java.awt.Color(51, 102, 255));
        jToolBar4.setRollover(true);
        jToolBar3.add(jToolBar4);

        jButton_crearEquipo.setBackground(new java.awt.Color(255, 51, 51));
        jButton_crearEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearEquipo.setText("Crear equipo");
        jButton_crearEquipo.setFocusable(false);
        jButton_crearEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_crearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearEquipoMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_crearEquipo);

        jButton_crearJugador.setBackground(new java.awt.Color(51, 51, 255));
        jButton_crearJugador.setForeground(new java.awt.Color(0, 0, 0));
        jButton_crearJugador.setText("Crear Jugador");
        jButton_crearJugador.setFocusable(false);
        jButton_crearJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crearJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_crearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearJugadorMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_crearJugador);

        jButton_transferencia.setBackground(new java.awt.Color(255, 255, 51));
        jButton_transferencia.setForeground(new java.awt.Color(0, 0, 0));
        jButton_transferencia.setText("Transferencia");
        jButton_transferencia.setFocusable(false);
        jButton_transferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_transferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_transferenciaMouseClicked(evt);
            }
        });
        jToolBar3.add(jButton_transferencia);

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(Barcita)
                .addGap(191, 191, 191))
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Barcita)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        jMenuBar_principal.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar_principal.setForeground(new java.awt.Color(0, 0, 0));

        jMenu_Opciones.setText("Opciones");

        jMenuItem_crearEquipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearEquipo.setText("crear Equipo");
        jMenuItem_crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_crearEquipoActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_crearEquipo);

        jMenuItem_crearJugador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_crearJugador.setText("Crear Jugador");
        jMenuItem_crearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_crearJugadorActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_crearJugador);

        jMenuItem_Transferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Transferencia.setText("Transferencia");
        jMenuItem_Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TransferenciaActionPerformed(evt);
            }
        });
        jMenu_Opciones.add(jMenuItem_Transferencia);

        jMenuBar_principal.add(jMenu_Opciones);

        jMenu_ayuda.setText("Ayuda");
        jMenuBar_principal.add(jMenu_ayuda);

        setJMenuBar(jMenuBar_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_crearEquipoActionPerformed
        // TODO add your handling code here:
        jDialog_CrearEquipo.setVisible(true);
        jDialog_CrearEquipo.pack();
    }//GEN-LAST:event_jMenuItem_crearEquipoActionPerformed

    private void jButton_crearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearEquipoMouseClicked
        // TODO add your handling code here:
        jDialog_CrearEquipo.setVisible(true);
        jDialog_CrearEquipo.pack();
    }//GEN-LAST:event_jButton_crearEquipoMouseClicked

    private void jMenuItem_crearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_crearJugadorActionPerformed
        // TODO add your handling code here:
        jDialog_CrearJugadores.setVisible(true);
        jDialog_CrearJugadores.pack();
        
    }//GEN-LAST:event_jMenuItem_crearJugadorActionPerformed

    private void jButton_crearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearJugadorMouseClicked
        // TODO add your handling code here:
        jDialog_CrearJugadores.setVisible(true);
        jDialog_CrearJugadores.pack();
    }//GEN-LAST:event_jButton_crearJugadorMouseClicked

    private void jMenuItem_TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TransferenciaActionPerformed
        // TODO add your handling code here:
        jDialog_Transferencia.setVisible(true);
        jDialog_Transferencia.pack();
    }//GEN-LAST:event_jMenuItem_TransferenciaActionPerformed

    private void jButton_transferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_transferenciaMouseClicked
        // TODO add your handling code here:
        jDialog_Transferencia.setVisible(true);
        jDialog_Transferencia.pack();
    }//GEN-LAST:event_jButton_transferenciaMouseClicked

    private void jTextField_crearEquipo_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_crearEquipo_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_crearEquipo_paisActionPerformed

    private void jButton_CrearEquipo_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearEquipo_addMouseClicked
        // TODO add your handling code here:
        Equipos.add(new Equipo(pais, nombre, estadio, cuidad))
    }//GEN-LAST:event_jButton_CrearEquipo_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fulbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fulbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcita;
    private javax.swing.JButton jButton_CrearEquipo_add;
    private javax.swing.JButton jButton_crearEquipo;
    private javax.swing.JButton jButton_crearJugador;
    private javax.swing.JButton jButton_transferencia;
    private javax.swing.JDialog jDialog_CrearEquipo;
    private javax.swing.JDialog jDialog_CrearJugadores;
    private javax.swing.JDialog jDialog_Transferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar_principal;
    private javax.swing.JMenuItem jMenuItem_Transferencia;
    private javax.swing.JMenuItem jMenuItem_crearEquipo;
    private javax.swing.JMenuItem jMenuItem_crearJugador;
    private javax.swing.JMenu jMenu_Opciones;
    private javax.swing.JMenu jMenu_ayuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JTextField jTextField_crearEquipo_Cuidad;
    private javax.swing.JTextField jTextField_crearEquipo_pais;
    private javax.swing.JTextField jTextField_crearequipo_estadio;
    private javax.swing.JTextField jTextField_crearequipo_nombre;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Jugador> Jugadores = new ArrayList();
    ArrayList<Equipo> Equipos = new ArrayList();
    
    
}
